---
driver_plugin: lxc

platforms:
- name: ubuntu-1204
  driver_config:
    base_container: ubuntu-1204
    username: ubuntu
    password: ubuntu

suites:
- name: default
  run_list: 
    - recipe[bprobe]
  attributes: {}